begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(19);
select has_table('public','guest_profiles','guest profiles exist');
select has_table('public','xp_transactions','immutable XP history exists');
select has_table('public','badges','badge catalog exists');
select has_table('public','profile_badges','badge ownership exists');
select has_table('public','achievements','achievement catalog exists');
select has_table('public','profile_achievements','achievement ownership exists');
select has_table('public','report_confirmations','implicit confirmations exist');
select has_function('public','claim_guest_progress','claim RPC exists');
select has_function('public','get_guest_gamification_summary','guest summary RPC exists');
select has_function('public','get_user_gamification_summary','user summary RPC exists');
select has_function('public','get_leaderboard','leaderboard RPC exists');
select has_function('public','submit_financial_service_report_with_rewards','reward-aware report RPC exists');
select is((select count(*) from public.badges where is_active),10::bigint,'ten initial badges are seeded');
select is((select count(*) from public.achievements where is_active),7::bigint,'seven initial achievements are seeded');
select is(public.gamification_level_for_xp(0),1,'zero XP is level one');
select is(public.gamification_level_for_xp(500),5,'500 XP is level five');
select is((public.gamification_level_progress(120)->>'nextLevelXp')::integer,150,'level progress returns next threshold');
select ok(not has_table_privilege('anon','public.guest_profiles','SELECT'),'guests cannot enumerate guest profiles');
select ok(not has_table_privilege('authenticated','public.xp_transactions','INSERT'),'clients cannot insert XP');
select * from finish();
rollback;
